# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
[[main]]
  name = "News"
  url = "#posts"
  weight = 20

[[main]]
  name = "Awards & Honors"
  url = "#accomplishments"
  weight = 25
  
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40
  
[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50
  
[[main]]
  name = "CV"
  url = "https://drive.google.com/file/d/1pYrGAeHVDJQNrpHGl7nGvy6ryODaZQ-m/view?usp=sharing"
  weight = 60

[[main]]
  name = "Google Scholar"
  url = "https://scholar.google.com/citations?user=bO3NtXMAAAAJ&hl=en&oi=ao"
  weight = 70

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
